name: 'Terraform Apply'

on:
  push:
    branches:
      - "main"

permissions:
  contents: read

jobs:
  terraform:
    runs-on: [self-hosted]
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Terraform Backend
        run: |
          cat > backend.tf << EOF
            terraform {
              backend "local" {
                path = "~/tfstate/${{env.GITHUB_REPOSITORY_ID}}/terraform.tfstate"
              }
            }
          EOF

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init

      # Checks that all Terraform configuration files adhere to a canonical format
      - name: Terraform Format
        run: terraform fmt -check

      # Generates an execution plan for Terraform
      - name: Terraform Plan
        env:
          TF_VAR_owner_name: ${{secrets.OWNER_NAME}}
          TF_VAR_owner_email: ${{secrets.OWNER_EMAIL}}
          TF_VAR_key_name: ${{secrets.KEY_NAME}}
          TF_VAR_tailscale_auth_key: ${{secrets.TAILSCALE_AUTH_KEY}}
        run: terraform plan -input=false

      - name: Terraform Apply
        env:
          TF_VAR_owner_name: ${{secrets.OWNER_NAME}}
          TF_VAR_owner_email: ${{secrets.OWNER_EMAIL}}
          TF_VAR_key_name: ${{secrets.KEY_NAME}}
          TF_VAR_tailscale_auth_key: ${{secrets.TAILSCALE_AUTH_KEY}}
        #if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false